"""Package and atomically select one set of production frontend bundles."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import tempfile
from datetime import UTC, datetime
from pathlib import Path
from urllib.parse import urlsplit

from vmshpwa.scripts.report_io import atomic_write_text


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
RELEASE_ROOT = REPOSITORY_ROOT / ".runtime" / "phase11-rehearsal" / "releases"
APP_SOURCES = {
    "student": REPOSITORY_ROOT / "vmshpwa" / "apps" / "student" / "dist",
    "family": REPOSITORY_ROOT / "vmshpwa" / "apps" / "family" / "dist",
    "staff": REPOSITORY_ROOT / "vmshpwa" / "apps" / "staff" / "dist",
}
BUILD_PROVENANCE_FILE = "build-provenance.json"
REQUIRED_FILES = {
    "student": ("index.html", "manifest.webmanifest", "sw.js", BUILD_PROVENANCE_FILE),
    "family": ("index.html", "manifest.webmanifest", "sw.js", BUILD_PROVENANCE_FILE),
    "staff": ("index.html", BUILD_PROVENANCE_FILE),
}
RELEASE_ID_PATTERN = re.compile(r"[a-z0-9][a-z0-9._-]{0,63}")


def _validate_release_id(release_id: str) -> None:
    if not RELEASE_ID_PATTERN.fullmatch(release_id) or release_id in {".", ".."}:
        raise ValueError("Release ID must be a short lowercase revision label")


def _tree_summary(root: Path) -> dict[str, object]:
    digest = hashlib.sha256()
    file_count = 0
    byte_count = 0
    for path in sorted(root.rglob("*")):
        if path.is_symlink():
            raise ValueError(f"Release bundle contains a symlink: {path}")
        if not path.is_file():
            continue
        relative_path = path.relative_to(root).as_posix()
        contents = path.read_bytes()
        digest.update(relative_path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(hashlib.sha256(contents).digest())
        file_count += 1
        byte_count += len(contents)
    return {
        "files": file_count,
        "bytes": byte_count,
        "sha256": digest.hexdigest(),
    }


def _exact_https_origin(value: object, *, field: str) -> str:
    if not isinstance(value, str):
        raise ValueError(f"Build provenance {field} must be an HTTPS origin")
    parsed = urlsplit(value)
    if (
        parsed.scheme != "https"
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.path
        or parsed.query
        or parsed.fragment
        or value != f"https://{parsed.netloc}"
    ):
        raise ValueError(f"Build provenance {field} must be an HTTPS origin")
    return value


def _read_build_provenance(
    root: Path, *, application: str, release_id: str
) -> dict[str, object]:
    """Validate the small public build receipt before packaging any bytes.

    The receipt is deliberately generated by Vite, not inferred from hashed
    JavaScript. This is the deploy boundary in Phase 11: a credential-free E2E
    build may be tested, but it cannot be selected as a production release.
    """

    path = root / BUILD_PROVENANCE_FILE
    if path.is_symlink() or not path.is_file() or path.stat().st_size > 4096:
        raise ValueError(f"Missing or invalid {application} build provenance")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ValueError(f"Unreadable {application} build provenance") from exc
    if not isinstance(value, dict):
        raise ValueError(f"Invalid {application} build provenance")
    expected_fixed = {
        "schemaVersion": 1,
        "application": application,
        "profile": "production",
        "releaseId": release_id,
        "sentryConfigured": True,
        "msw": False,
        "prototype": False,
    }
    if any(value.get(name) != expected for name, expected in expected_fixed.items()):
        raise ValueError(f"Invalid {application} build provenance")
    return {
        "profile": "production",
        "releaseId": release_id,
        "publicMediaOrigin": _exact_https_origin(
            value.get("publicMediaOrigin"), field="publicMediaOrigin"
        ),
        "sentryConfigured": True,
        "sentryOrigin": _exact_https_origin(
            value.get("sentryOrigin"), field="sentryOrigin"
        ),
        "msw": False,
        "prototype": False,
    }


def package_release(
    release_id: str,
    recorded_at: str,
    *,
    sources: dict[str, Path] | None = None,
    release_root: Path | None = None,
) -> dict[str, object]:
    """Copy three complete builds into a new immutable release directory."""

    _validate_release_id(release_id)
    source_directories = APP_SOURCES if sources is None else sources
    if set(source_directories) != set(REQUIRED_FILES):
        raise ValueError("Exactly the student, family and staff bundles are required")

    build_provenance: dict[str, object] | None = None
    for app_name, required_files in REQUIRED_FILES.items():
        source = source_directories[app_name]
        if not source.is_dir():
            raise ValueError(f"Missing {app_name} production bundle")
        for relative_path in required_files:
            if not (source / relative_path).is_file():
                raise ValueError(f"Missing {app_name}/{relative_path}")
        application_provenance = _read_build_provenance(
            source, application=app_name, release_id=release_id
        )
        if build_provenance is None:
            build_provenance = application_provenance
        elif application_provenance != build_provenance:
            raise ValueError("Frontend applications have different build provenance")

    if build_provenance is None:  # pragma: no cover - guarded by exact app set
        raise ValueError("Build provenance is missing")

    selected_release_root = RELEASE_ROOT if release_root is None else release_root
    selected_release_root.mkdir(parents=True, exist_ok=True)
    destination = selected_release_root / release_id
    if destination.exists():
        raise ValueError("Release directory already exists")

    staging = Path(
        tempfile.mkdtemp(prefix=f".{release_id}.", dir=selected_release_root)
    )
    try:
        applications: dict[str, object] = {}
        for app_name, source in source_directories.items():
            app_destination = staging / app_name
            shutil.copytree(source, app_destination)
            applications[app_name] = _tree_summary(app_destination)

        manifest = {
            "schemaVersion": 1,
            "releaseId": release_id,
            "recordedAt": recorded_at,
            "build": build_provenance,
            "applications": applications,
        }
        (staging / "release.json").write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        os.replace(staging, destination)
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise

    return manifest


def verify_release(
    release_id: str,
    recorded_at: str,
    *,
    release_root: Path | None = None,
) -> dict[str, object]:
    """Verify an immutable release against the manifest written at packaging."""

    _validate_release_id(release_id)
    selected_release_root = RELEASE_ROOT if release_root is None else release_root
    release = selected_release_root / release_id
    manifest_path = release / "release.json"
    if (
        release.is_symlink()
        or not release.is_dir()
        or manifest_path.is_symlink()
        or not manifest_path.is_file()
    ):
        raise ValueError("Release directory is missing or incomplete")

    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ValueError("Release manifest is unreadable") from exc
    if not isinstance(manifest, dict):
        raise ValueError("Release manifest must be an object")
    if manifest.get("schemaVersion") != 1 or manifest.get("releaseId") != release_id:
        raise ValueError("Release manifest identity does not match the release")
    recorded_applications = manifest.get("applications")
    if not isinstance(recorded_applications, dict) or set(recorded_applications) != set(
        REQUIRED_FILES
    ):
        raise ValueError("Release manifest must describe all three applications")
    recorded_build = manifest.get("build")
    if not isinstance(recorded_build, dict):
        raise ValueError("Release manifest must contain build provenance")

    expected_root_entries = {*REQUIRED_FILES, "release.json"}
    if {path.name for path in release.iterdir()} != expected_root_entries:
        raise ValueError("Release directory contains unexpected or missing entries")

    verified_applications: dict[str, object] = {}
    for app_name, required_files in REQUIRED_FILES.items():
        app_root = release / app_name
        if app_root.is_symlink() or not app_root.is_dir():
            raise ValueError(f"Missing {app_name} production bundle")
        for relative_path in required_files:
            if not (app_root / relative_path).is_file():
                raise ValueError(f"Missing {app_name}/{relative_path}")
        if (
            _read_build_provenance(
                app_root, application=app_name, release_id=release_id
            )
            != recorded_build
        ):
            raise ValueError(f"Release build provenance failed for {app_name}")
        actual_summary = _tree_summary(app_root)
        if recorded_applications[app_name] != actual_summary:
            raise ValueError(f"Release integrity check failed for {app_name}")
        verified_applications[app_name] = actual_summary

    return {
        "schemaVersion": 1,
        "operation": "static-release-verify",
        "recordedAt": recorded_at,
        "releaseId": release_id,
        "build": recorded_build,
        "applications": verified_applications,
    }


def activate_release(
    release_id: str,
    recorded_at: str,
    *,
    action: str = "activate",
    release_root: Path | None = None,
) -> dict[str, object]:
    """Atomically point ``current`` at an existing release."""

    _validate_release_id(release_id)
    selected_release_root = RELEASE_ROOT if release_root is None else release_root
    destination = selected_release_root / release_id
    current = selected_release_root / "current"
    if current.exists() and not current.is_symlink():
        raise ValueError("The current release path exists and is not a symlink")
    # Activation and rollback use the same fail-closed integrity gate. This is
    # the concrete immutable-release decision from Phase 11, not a best-effort
    # check of whether release.json merely exists.
    verify_release(release_id, recorded_at, release_root=selected_release_root)
    previous_release_id = (
        current.readlink().as_posix() if current.is_symlink() else None
    )

    temporary = selected_release_root / f".current.{os.getpid()}"
    if temporary.exists() or temporary.is_symlink():
        raise ValueError("Temporary activation link already exists")
    try:
        temporary.symlink_to(release_id)
        os.replace(temporary, current)
    finally:
        temporary.unlink(missing_ok=True)

    if current.resolve() != destination.resolve():
        raise RuntimeError(
            "Activated release does not resolve to the requested directory"
        )
    return {
        "schemaVersion": 1,
        "operation": f"static-release-{action}",
        "recordedAt": recorded_at,
        "releaseId": release_id,
        "previousReleaseId": previous_release_id,
        "currentLinkTarget": current.readlink().as_posix(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=("package", "verify", "activate", "rollback"))
    parser.add_argument("--release-id", required=True)
    parser.add_argument(
        "--release-root",
        type=Path,
        required=True,
        help="dedicated static release directory outside the deployment checkout",
    )
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument(
        "--recorded-at",
        default=datetime.now(UTC).isoformat().replace("+00:00", "Z"),
    )
    arguments = parser.parse_args()

    if arguments.action == "package":
        report = package_release(
            arguments.release_id,
            arguments.recorded_at,
            release_root=arguments.release_root,
        )
    elif arguments.action == "verify":
        report = verify_release(
            arguments.release_id,
            arguments.recorded_at,
            release_root=arguments.release_root,
        )
    else:
        report = activate_release(
            arguments.release_id,
            arguments.recorded_at,
            action=arguments.action,
            release_root=arguments.release_root,
        )
    atomic_write_text(
        arguments.report,
        json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    )
    print(json.dumps(report, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
