/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChildrenRouteImport } from './routes/children'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OrganizersRouteImport } from './routes/organizers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ChildrenIndexRouteImport } from './routes/children.index'
import { Route as ChildrenChildIdRouteImport } from './routes/children.$childId'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsPostIdRouteImport } from './routes/news.$postId'
import { Route as OrganizersIndexRouteImport } from './routes/organizers.index'
import { Route as OrganizersThreadIdRouteImport } from './routes/organizers.$threadId'
import { Route as OrganizersNewRouteImport } from './routes/organizers.new'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as TasksCourseCodeGroupCodeLessonNumberRouteImport } from './routes/tasks.$courseCode.$groupCode.$lessonNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenRoute = ChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersRoute = OrganizersRouteImport.update({
  id: '/organizers',
  path: '/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenIndexRoute = ChildrenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChildrenRoute,
} as any)
const ChildrenChildIdRoute = ChildrenChildIdRouteImport.update({
  id: '/$childId',
  path: '/$childId',
  getParentRoute: () => ChildrenRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsPostIdRoute = NewsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => NewsRoute,
} as any)
const OrganizersIndexRoute = OrganizersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizersRoute,
} as any)
const OrganizersThreadIdRoute = OrganizersThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => OrganizersRoute,
} as any)
const OrganizersNewRoute = OrganizersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrganizersRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRoute,
} as any)
const TasksCourseCodeGroupCodeLessonNumberRoute =
  TasksCourseCodeGroupCodeLessonNumberRouteImport.update({
    id: '/tasks/$courseCode/$groupCode/$lessonNumber',
    path: '/tasks/$courseCode/$groupCode/$lessonNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/children': typeof ChildrenRouteWithChildren
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/organizers': typeof OrganizersRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/children/$childId': typeof ChildrenChildIdRoute
  '/news/$postId': typeof NewsPostIdRoute
  '/organizers/$threadId': typeof OrganizersThreadIdRoute
  '/organizers/new': typeof OrganizersNewRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/children/': typeof ChildrenIndexRoute
  '/news/': typeof NewsIndexRoute
  '/organizers/': typeof OrganizersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tasks/$courseCode/$groupCode/$lessonNumber': typeof TasksCourseCodeGroupCodeLessonNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/news/$postId': typeof NewsPostIdRoute
  '/organizers/$threadId': typeof OrganizersThreadIdRoute
  '/organizers/new': typeof OrganizersNewRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/children': typeof ChildrenIndexRoute
  '/news': typeof NewsIndexRoute
  '/organizers': typeof OrganizersIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/tasks/$courseCode/$groupCode/$lessonNumber': typeof TasksCourseCodeGroupCodeLessonNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/children': typeof ChildrenRouteWithChildren
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/organizers': typeof OrganizersRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/children/$childId': typeof ChildrenChildIdRoute
  '/news/$postId': typeof NewsPostIdRoute
  '/organizers/$threadId': typeof OrganizersThreadIdRoute
  '/organizers/new': typeof OrganizersNewRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/children/': typeof ChildrenIndexRoute
  '/news/': typeof NewsIndexRoute
  '/organizers/': typeof OrganizersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/tasks/$courseCode/$groupCode/$lessonNumber': typeof TasksCourseCodeGroupCodeLessonNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/children'
    | '/login'
    | '/news'
    | '/organizers'
    | '/profile'
    | '/children/$childId'
    | '/news/$postId'
    | '/organizers/$threadId'
    | '/organizers/new'
    | '/profile/notifications'
    | '/children/'
    | '/news/'
    | '/organizers/'
    | '/profile/'
    | '/tasks/$courseCode/$groupCode/$lessonNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/children/$childId'
    | '/news/$postId'
    | '/organizers/$threadId'
    | '/organizers/new'
    | '/profile/notifications'
    | '/children'
    | '/news'
    | '/organizers'
    | '/profile'
    | '/tasks/$courseCode/$groupCode/$lessonNumber'
  id:
    | '__root__'
    | '/'
    | '/children'
    | '/login'
    | '/news'
    | '/organizers'
    | '/profile'
    | '/children/$childId'
    | '/news/$postId'
    | '/organizers/$threadId'
    | '/organizers/new'
    | '/profile/notifications'
    | '/children/'
    | '/news/'
    | '/organizers/'
    | '/profile/'
    | '/tasks/$courseCode/$groupCode/$lessonNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChildrenRoute: typeof ChildrenRouteWithChildren
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  OrganizersRoute: typeof OrganizersRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  TasksCourseCodeGroupCodeLessonNumberRoute: typeof TasksCourseCodeGroupCodeLessonNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children': {
      id: '/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof ChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers': {
      id: '/organizers'
      path: '/organizers'
      fullPath: '/organizers'
      preLoaderRoute: typeof OrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/': {
      id: '/children/'
      path: '/'
      fullPath: '/children/'
      preLoaderRoute: typeof ChildrenIndexRouteImport
      parentRoute: typeof ChildrenRoute
    }
    '/children/$childId': {
      id: '/children/$childId'
      path: '/$childId'
      fullPath: '/children/$childId'
      preLoaderRoute: typeof ChildrenChildIdRouteImport
      parentRoute: typeof ChildrenRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$postId': {
      id: '/news/$postId'
      path: '/$postId'
      fullPath: '/news/$postId'
      preLoaderRoute: typeof NewsPostIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/organizers/': {
      id: '/organizers/'
      path: '/'
      fullPath: '/organizers/'
      preLoaderRoute: typeof OrganizersIndexRouteImport
      parentRoute: typeof OrganizersRoute
    }
    '/organizers/$threadId': {
      id: '/organizers/$threadId'
      path: '/$threadId'
      fullPath: '/organizers/$threadId'
      preLoaderRoute: typeof OrganizersThreadIdRouteImport
      parentRoute: typeof OrganizersRoute
    }
    '/organizers/new': {
      id: '/organizers/new'
      path: '/new'
      fullPath: '/organizers/new'
      preLoaderRoute: typeof OrganizersNewRouteImport
      parentRoute: typeof OrganizersRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/tasks/$courseCode/$groupCode/$lessonNumber': {
      id: '/tasks/$courseCode/$groupCode/$lessonNumber'
      path: '/tasks/$courseCode/$groupCode/$lessonNumber'
      fullPath: '/tasks/$courseCode/$groupCode/$lessonNumber'
      preLoaderRoute: typeof TasksCourseCodeGroupCodeLessonNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChildrenRouteChildren {
  ChildrenChildIdRoute: typeof ChildrenChildIdRoute
  ChildrenIndexRoute: typeof ChildrenIndexRoute
}

const ChildrenRouteChildren: ChildrenRouteChildren = {
  ChildrenChildIdRoute: ChildrenChildIdRoute,
  ChildrenIndexRoute: ChildrenIndexRoute,
}

const ChildrenRouteWithChildren = ChildrenRoute._addFileChildren(
  ChildrenRouteChildren,
)

interface NewsRouteChildren {
  NewsPostIdRoute: typeof NewsPostIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsPostIdRoute: NewsPostIdRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface OrganizersRouteChildren {
  OrganizersThreadIdRoute: typeof OrganizersThreadIdRoute
  OrganizersNewRoute: typeof OrganizersNewRoute
  OrganizersIndexRoute: typeof OrganizersIndexRoute
}

const OrganizersRouteChildren: OrganizersRouteChildren = {
  OrganizersThreadIdRoute: OrganizersThreadIdRoute,
  OrganizersNewRoute: OrganizersNewRoute,
  OrganizersIndexRoute: OrganizersIndexRoute,
}

const OrganizersRouteWithChildren = OrganizersRoute._addFileChildren(
  OrganizersRouteChildren,
)

interface ProfileRouteChildren {
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChildrenRoute: ChildrenRouteWithChildren,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  OrganizersRoute: OrganizersRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  TasksCourseCodeGroupCodeLessonNumberRoute:
    TasksCourseCodeGroupCodeLessonNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
