/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BroadcastsRouteImport } from './routes/broadcasts'
import { Route as ClassroomsRouteImport } from './routes/classrooms'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OralRouteImport } from './routes/oral'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as ReactionsRouteImport } from './routes/reactions'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as UsersRouteImport } from './routes/users'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as ProblemsProblemIdRouteImport } from './routes/problems.$problemId'
import { Route as QuestionsIndexRouteImport } from './routes/questions.index'
import { Route as QuestionsThreadIdRouteImport } from './routes/questions.$threadId'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewSubmissionIdRouteImport } from './routes/review.$submissionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastsRoute = BroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomsRoute = ClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OralRoute = OralRouteImport.update({
  id: '/oral',
  path: '/oral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactionsRoute = ReactionsRouteImport.update({
  id: '/reactions',
  path: '/reactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LessonsRoute,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProblemsRoute,
} as any)
const ProblemsProblemIdRoute = ProblemsProblemIdRouteImport.update({
  id: '/$problemId',
  path: '/$problemId',
  getParentRoute: () => ProblemsRoute,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestionsRoute,
} as any)
const QuestionsThreadIdRoute = QuestionsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => QuestionsRoute,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewSubmissionIdRoute = ReviewSubmissionIdRouteImport.update({
  id: '/$submissionId',
  path: '/$submissionId',
  getParentRoute: () => ReviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/broadcasts': typeof BroadcastsRoute
  '/classrooms': typeof ClassroomsRoute
  '/courses': typeof CoursesRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/oral': typeof OralRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/questions': typeof QuestionsRouteWithChildren
  '/reactions': typeof ReactionsRoute
  '/review': typeof ReviewRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/users': typeof UsersRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/questions/$threadId': typeof QuestionsThreadIdRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
  '/lessons/': typeof LessonsIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/review/': typeof ReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/broadcasts': typeof BroadcastsRoute
  '/classrooms': typeof ClassroomsRoute
  '/courses': typeof CoursesRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/oral': typeof OralRoute
  '/reactions': typeof ReactionsRoute
  '/statistics': typeof StatisticsRoute
  '/users': typeof UsersRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/questions/$threadId': typeof QuestionsThreadIdRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
  '/lessons': typeof LessonsIndexRoute
  '/problems': typeof ProblemsIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/review': typeof ReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/broadcasts': typeof BroadcastsRoute
  '/classrooms': typeof ClassroomsRoute
  '/courses': typeof CoursesRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/oral': typeof OralRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/questions': typeof QuestionsRouteWithChildren
  '/reactions': typeof ReactionsRoute
  '/review': typeof ReviewRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/users': typeof UsersRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/questions/$threadId': typeof QuestionsThreadIdRoute
  '/review/$submissionId': typeof ReviewSubmissionIdRoute
  '/lessons/': typeof LessonsIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/review/': typeof ReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/broadcasts'
    | '/classrooms'
    | '/courses'
    | '/lessons'
    | '/login'
    | '/news'
    | '/oral'
    | '/problems'
    | '/questions'
    | '/reactions'
    | '/review'
    | '/statistics'
    | '/users'
    | '/lessons/$lessonId'
    | '/problems/$problemId'
    | '/questions/$threadId'
    | '/review/$submissionId'
    | '/lessons/'
    | '/problems/'
    | '/questions/'
    | '/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/broadcasts'
    | '/classrooms'
    | '/courses'
    | '/login'
    | '/news'
    | '/oral'
    | '/reactions'
    | '/statistics'
    | '/users'
    | '/lessons/$lessonId'
    | '/problems/$problemId'
    | '/questions/$threadId'
    | '/review/$submissionId'
    | '/lessons'
    | '/problems'
    | '/questions'
    | '/review'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/broadcasts'
    | '/classrooms'
    | '/courses'
    | '/lessons'
    | '/login'
    | '/news'
    | '/oral'
    | '/problems'
    | '/questions'
    | '/reactions'
    | '/review'
    | '/statistics'
    | '/users'
    | '/lessons/$lessonId'
    | '/problems/$problemId'
    | '/questions/$threadId'
    | '/review/$submissionId'
    | '/lessons/'
    | '/problems/'
    | '/questions/'
    | '/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BroadcastsRoute: typeof BroadcastsRoute
  ClassroomsRoute: typeof ClassroomsRoute
  CoursesRoute: typeof CoursesRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  OralRoute: typeof OralRoute
  ProblemsRoute: typeof ProblemsRouteWithChildren
  QuestionsRoute: typeof QuestionsRouteWithChildren
  ReactionsRoute: typeof ReactionsRoute
  ReviewRoute: typeof ReviewRouteWithChildren
  StatisticsRoute: typeof StatisticsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcasts': {
      id: '/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof BroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classrooms': {
      id: '/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof ClassroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oral': {
      id: '/oral'
      path: '/oral'
      fullPath: '/oral'
      preLoaderRoute: typeof OralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reactions': {
      id: '/reactions'
      path: '/reactions'
      fullPath: '/reactions'
      preLoaderRoute: typeof ReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/problems/': {
      id: '/problems/'
      path: '/'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/problems/$problemId': {
      id: '/problems/$problemId'
      path: '/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof ProblemsProblemIdRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/questions/': {
      id: '/questions/'
      path: '/'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/questions/$threadId': {
      id: '/questions/$threadId'
      path: '/$threadId'
      fullPath: '/questions/$threadId'
      preLoaderRoute: typeof QuestionsThreadIdRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/$submissionId': {
      id: '/review/$submissionId'
      path: '/$submissionId'
      fullPath: '/review/$submissionId'
      preLoaderRoute: typeof ReviewSubmissionIdRouteImport
      parentRoute: typeof ReviewRoute
    }
  }
}

interface LessonsRouteChildren {
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  LessonsIndexRoute: LessonsIndexRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

interface ProblemsRouteChildren {
  ProblemsProblemIdRoute: typeof ProblemsProblemIdRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
  ProblemsProblemIdRoute: ProblemsProblemIdRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
  ProblemsRouteChildren,
)

interface QuestionsRouteChildren {
  QuestionsThreadIdRoute: typeof QuestionsThreadIdRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
}

const QuestionsRouteChildren: QuestionsRouteChildren = {
  QuestionsThreadIdRoute: QuestionsThreadIdRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
}

const QuestionsRouteWithChildren = QuestionsRoute._addFileChildren(
  QuestionsRouteChildren,
)

interface ReviewRouteChildren {
  ReviewSubmissionIdRoute: typeof ReviewSubmissionIdRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewSubmissionIdRoute: ReviewSubmissionIdRoute,
  ReviewIndexRoute: ReviewIndexRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BroadcastsRoute: BroadcastsRoute,
  ClassroomsRoute: ClassroomsRoute,
  CoursesRoute: CoursesRoute,
  LessonsRoute: LessonsRouteWithChildren,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  OralRoute: OralRoute,
  ProblemsRoute: ProblemsRouteWithChildren,
  QuestionsRoute: QuestionsRouteWithChildren,
  ReactionsRoute: ReactionsRoute,
  ReviewRoute: ReviewRouteWithChildren,
  StatisticsRoute: StatisticsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
