server {
    listen 80;
    listen [::]:80;

    server_name grafprep.leaders.tech;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name grafprep.leaders.tech;

    ssl_certificate /etc/letsencrypt/live/grafprep.leaders.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grafprep.leaders.tech/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000" always;

    access_log off;
    error_log /var/log/nginx/grafprep.error.log warn;

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $tlf_grafana_connection_upgrade;

        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        client_max_body_size 10m;
    }
}
