/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsPostIdRouteImport } from './routes/news.$postId'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as QuestionsIndexRouteImport } from './routes/questions.index'
import { Route as QuestionsThreadIdRouteImport } from './routes/questions.$threadId'
import { Route as QuestionsNewRouteImport } from './routes/questions.new'
import { Route as SubmissionsSubmissionIdRouteImport } from './routes/submissions.$submissionId'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsPostIdRoute = NewsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => NewsRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRoute,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestionsRoute,
} as any)
const QuestionsThreadIdRoute = QuestionsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => QuestionsRoute,
} as any)
const QuestionsNewRoute = QuestionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuestionsRoute,
} as any)
const SubmissionsSubmissionIdRoute = SubmissionsSubmissionIdRouteImport.update({
  id: '/submissions/$submissionId',
  path: '/submissions/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/progress': typeof ProgressRoute
  '/questions': typeof QuestionsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/news/$postId': typeof NewsPostIdRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/questions/$threadId': typeof QuestionsThreadIdRoute
  '/questions/new': typeof QuestionsNewRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/news/': typeof NewsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/news/$postId': typeof NewsPostIdRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/questions/$threadId': typeof QuestionsThreadIdRoute
  '/questions/new': typeof QuestionsNewRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/news': typeof NewsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/progress': typeof ProgressRoute
  '/questions': typeof QuestionsRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/news/$postId': typeof NewsPostIdRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/questions/$threadId': typeof QuestionsThreadIdRoute
  '/questions/new': typeof QuestionsNewRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/news/': typeof NewsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/news'
    | '/profile'
    | '/progress'
    | '/questions'
    | '/tasks'
    | '/news/$postId'
    | '/profile/notifications'
    | '/questions/$threadId'
    | '/questions/new'
    | '/submissions/$submissionId'
    | '/tasks/$taskId'
    | '/news/'
    | '/profile/'
    | '/questions/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/progress'
    | '/news/$postId'
    | '/profile/notifications'
    | '/questions/$threadId'
    | '/questions/new'
    | '/submissions/$submissionId'
    | '/tasks/$taskId'
    | '/news'
    | '/profile'
    | '/questions'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/news'
    | '/profile'
    | '/progress'
    | '/questions'
    | '/tasks'
    | '/news/$postId'
    | '/profile/notifications'
    | '/questions/$threadId'
    | '/questions/new'
    | '/submissions/$submissionId'
    | '/tasks/$taskId'
    | '/news/'
    | '/profile/'
    | '/questions/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  QuestionsRoute: typeof QuestionsRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
  SubmissionsSubmissionIdRoute: typeof SubmissionsSubmissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$postId': {
      id: '/news/$postId'
      path: '/$postId'
      fullPath: '/news/$postId'
      preLoaderRoute: typeof NewsPostIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/questions/': {
      id: '/questions/'
      path: '/'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/questions/$threadId': {
      id: '/questions/$threadId'
      path: '/$threadId'
      fullPath: '/questions/$threadId'
      preLoaderRoute: typeof QuestionsThreadIdRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/questions/new': {
      id: '/questions/new'
      path: '/new'
      fullPath: '/questions/new'
      preLoaderRoute: typeof QuestionsNewRouteImport
      parentRoute: typeof QuestionsRoute
    }
    '/submissions/$submissionId': {
      id: '/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof SubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
  }
}

interface NewsRouteChildren {
  NewsPostIdRoute: typeof NewsPostIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsPostIdRoute: NewsPostIdRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ProfileRouteChildren {
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface QuestionsRouteChildren {
  QuestionsThreadIdRoute: typeof QuestionsThreadIdRoute
  QuestionsNewRoute: typeof QuestionsNewRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
}

const QuestionsRouteChildren: QuestionsRouteChildren = {
  QuestionsThreadIdRoute: QuestionsThreadIdRoute,
  QuestionsNewRoute: QuestionsNewRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
}

const QuestionsRouteWithChildren = QuestionsRoute._addFileChildren(
  QuestionsRouteChildren,
)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ProgressRoute: ProgressRoute,
  QuestionsRoute: QuestionsRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
  SubmissionsSubmissionIdRoute: SubmissionsSubmissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
